### ISSUE TITLE
great work! i'm looking forward to your code！

### ISSUE THREAD

**Issue by ldxbaby756** [UKPLab/kg2text#1]

**Comment by wutaiqiang** [comment]
Looking Forward too

**Comment by abevieiramota** [comment]
Me too

**Comment by Muzixin** [comment]
Looking Forward too

**Comment by wutaiqiang** [comment]
2 month past and remain the readme file

**Comment by DengYaosheng** [comment]
2 month and 3 hours past and remain the readme file

**Comment by leoribeiro** [comment]
Please, find the updated code that we released in the repo. I'm sorry for the delay. The paper was under review. We needed to wait for the review process to update and release the code.
