### ISSUE TITLE
error：”from torch_geometric.utils import scatter_‘’

### ISSUE THREAD

**Issue by wutaiqiang** [UKPLab/kg2text#2]
@leoribeiro hey，i am working on your code, An error occured when i was runing the 'preprocess_Agenda.sh'
![image](https://user-images.githubusercontent.com/28387419/87009861-5a582e00-c1f8-11ea-98df-dad4725a7db0.png)
here are my packege installed:
![image](https://user-images.githubusercontent.com/28387419/87009925-6fcd5800-c1f8-11ea-88b3-5a2242201a7f.png)

**Comment by wutaiqiang** [comment]
the code seems to be wrong is in 'graph2text/onmt/encoders/message_passing.py'

**Comment by leoribeiro** [comment]
Hi @wutaiqiang 

Please, note the versions of torch and torch-geometric in our README:
PyTorch 1.1.0
PyTorch Geometric 1.3.1

**Comment by wutaiqiang** [comment]
@leoribeiro thanks for your advice ,could you plz show me the version for **torch_scatter** and other kit for **torch geometric**?

**Comment by wutaiqiang** [comment]
![image](https://user-images.githubusercontent.com/28387419/87228160-deb1d900-c3d1-11ea-916d-a12774950dc9.png)

**Comment by leoribeiro** [comment]
These are the versions used:

torch - 1.1.0
torch-cluster - 1.4.4
torch-geometric - 1.3.1
torch-scatter - 1.3.1
torch-sparse -  0.4.0
torch-spline-conv -  1.1.0

**Comment by wutaiqiang** [comment]
@leoribeiro Thanks for your help！i solve the problem by replacing the old function in PYG1.3.1 with new funciton in PYG1.5.1
what is more，could you plz tell me how to use **multi-GPU**since one GPU is out of memory?

**Comment by leoribeiro** [comment]
Hi @wutaiqiang ,
We used a GPU with 32GB of memory in our experiments. If you are using a GPU with smaller memory, please, consider lowering the batch size.

**Comment by wutaiqiang** [comment]
ok，thank you for your kind help~

**Comment by tangxiangru** [comment]
> replacing the old function in PYG1.3.1 with new funciton in PYG1.5.1

Hi, I met the same problem. Could you explain how to replace the old function in PYG1.3.1 with new funciton in PYG1.5.1?

**Comment by wutaiqiang** [comment]
which code to modify：
         you can run the code to see where the error occurs
how to modify:
        Read the official doc for PYG1.3.1 and 1.5.1,then you can change it
two place to modify:
https://pytorch-geometric.readthedocs.io/en/1.3.1/modules/utils.html -->https://pytorch-scatter.readthedocs.io/en/2.0.2/functions/scatter.html
https://pytorch-geometric.readthedocs.io/en/1.3.1/modules/utils.html-->https://pytorch-geometric.readthedocs.io/en/latest/modules/utils.html

**Comment by tangxiangru** [comment]
> which code to modify：
> you can run the code to see where the error occurs
> how to modify:
> Read the official doc for PYG1.3.1 and 1.5.1,then you can change it
> two place to modify:
> https://pytorch-geometric.readthedocs.io/en/1.3.1/modules/utils.html -->https://pytorch-scatter.readthedocs.io/en/2.0.2/functions/scatter.html
> [https://pytorch-geometric.readthedocs.io/en/1.3.1/modules/utils.html-->https://pytorch-geometric.readthedocs.io/en/latest/modules/utils.html](https://pytorch-geometric.readthedocs.io/en/1.3.1/modules/utils.html--%3Ehttps://pytorch-geometric.readthedocs.io/en/latest/modules/utils.html)

Thanks! Are you still using torch - 1.4.0?

**Comment by wutaiqiang** [comment]
> > which code to modify：
> > you can run the code to see where the error occurs
> > how to modify:
> > Read the official doc for PYG1.3.1 and 1.5.1,then you can change it
> > two place to modify:
> > https://pytorch-geometric.readthedocs.io/en/1.3.1/modules/utils.html -->https://pytorch-scatter.readthedocs.io/en/2.0.2/functions/scatter.html
> > [https://pytorch-geometric.readthedocs.io/en/1.3.1/modules/utils.html-->https://pytorch-geometric.readthedocs.io/en/latest/modules/utils.html](https://pytorch-geometric.readthedocs.io/en/1.3.1/modules/utils.html--%3Ehttps://pytorch-geometric.readthedocs.io/en/latest/modules/utils.html)
> 
> Thanks! Are you still using torch - 1.4.0?

yeap
