### ISSUE TITLE
A little error about the running script command

### ISSUE THREAD

**Issue by charfole** [UKPLab/kg2text#3]
@leoribeiro Hey! As shown in your README, the training scripts should be run like that.
```
./train_AGENDA.sh <graph_encoder> <gpu_id>
```
```
./train_WEBNLG.sh <graph_encoder> <gpu_id>
```
However, it will cause error because of the wrong position of two parameters (i. e. <graph_encoder> and <gpu_id>). 
After I modified it to `./train_WEBNLG.sh <gpu_id> <graph_encoder>` and it worked.

**Comment by leoribeiro** [comment]
Thanks for this information!
