### ISSUE TITLE
Some problems about WebNLG data

### ISSUE THREAD

**Issue by StevenTang1998** [UKPLab/kg2text#4]
Thanks for contributing your source code and guidance. 
I am a little confused about the WebNLG data. In your provided download link, I have found many versions, and I guess it may be downloaded in [https://gitlab.com/shimorina/webnlg-dataset/-/tree/master/webnlg_challenge_2017](https://gitlab.com/shimorina/webnlg-dataset/-/tree/master/webnlg_challenge_2017). However, after downing, I found the number of train, test and valid datasets inconsistent with the number provided in your original paper. And they cannot be processed by your `preprocess_WEBNLG.sh`.
Hence, could you provide the direct download link of WebNLG data using in your paper?

**Comment by SkyFishMoon** [comment]
hello, have you already resolved this problem?

**Comment by StevenTang1998** [comment]
Just download from [https://gitlab.com/shimorina/webnlg-dataset/-/tree/master/webnlg_challenge_2017](https://gitlab.com/shimorina/webnlg-dataset/-/tree/master/webnlg_challenge_2017), and then use the provided `preprocess_WEBNLG.sh` to process it.

**Comment by SkyFishMoon** [comment]
thanks very much for your reply. And have you replicated the paper's results on the webnlg dataset?  I evaluated the given decoding output and can't get the result reported in the paper

**Comment by StevenTang1998** [comment]
There is indeed a little gap. My result is `BLEU`: 48.60, `METEOR`: 42.47, `CHRF++`: 58.66.

**Comment by SkyFishMoon** [comment]
But the reported score of BLEU is 60+, maybe not a little gap I'm not sure about whether the provided output_webnlg.txt has already been relexicalised

**Comment by head-bigandhard** [comment]
Hello，I download the dataset from the web, but i can't run the code. Can I ask you some questions?

**Comment by StevenTang1998** [comment]
OK
